name: Test Docker on GitHub Actions

on:
  push:
    branches: 
      - main

jobs:
  push_container:
    runs-on: ubuntu-latest
    container:
      image: docker:27.5.0-rc.1-dind
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Test Docker
        run: |
          docker version
          docker info          
          docker build -t myapp:latest .