name: Test Docker on GitHub Actions

on:
  push:
    branches: 
      - main

jobs:
  push_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Test Docker
        run: |
          docker version
          docker info          