name: Test Docker on GitHub Actions

on:
  push:
    branches: 
      - main

jobs:
  push_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    container:
      image: docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Test Docker
        run: |
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV
          export
          docker version
          docker info          