name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build and Test NPM Package
  npm_build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a file in job1 
      run: |
        cd /home/runner/work
        ls -al 
        touch newfile.txt
        ls -al


  # Job 2: Build Docker Image
  docker_build:
    runs-on: ubuntu-latest
    needs: npm_build_and_test # Ensures npm job runs first

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker image ls 
        ls -al /home/runner/work


