name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default_docker:
    runs-on: ubuntu-latest
    steps:
    - name: verify default docker version
      run: |
        docker version
        docker info
      
  # Job 1: Build and Test NPM Package
  npm_build_and_test:
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:24-dind
          options: |
            --privileged 
          ports:
            - 2375:2375 # Expose Docker API port
          env:
            DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or specify the version your project uses

    - name: Verify Docker in Service
      run: |
          export DOCKER_HOST=http://localhost:2375
          docker version
          docker info

    - name: Build Docker image
      run: |
        docker info
        docker build -t myapp:latest .




