name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default_docker:
    runs-on: ubuntu-latest
    steps:
    - name: verify default docker version
      run: |
        docker version
        docker info
      
  # Job 1: Build and Test NPM Package
  npm_build_and_test:
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:24-dind
          options: --privileged
          ports:
            - 2375:2375 # Expose Docker API port
          env:
            DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker CLI
      uses: docker/setup-buildx-action@v2

    - name: Set DOCKER_HOST environment variable
      run: echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

    - name: Verify Docker in Service
      run: |
          echo $DOCKER_HOST
          docker version
          docker info
          echo $GITHUB_ENV

    - name: Build Docker image
      run: |
        echo $DOCKER_HOST
        docker info
        docker build -t myapp:latest .




